# Usar la imagen base de Python 3.13 con Alpine Linux
FROM python:3.13-alpine

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /capybarafilms/

# Instalar las dependencias del sistema necesarias para compilar y usar psycopg2
RUN apk add --no-cache gcc musl-dev libpq-dev postgresql-libs

# Copiar los archivos del proyecto al contenedor
COPY . /capybarafilms/

# Instalar las dependencias de Python desde requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Establecer el comando predeterminado para ejecutar la aplicación
CMD ["python", "CapybaraFilms/main.py"]